window.ROAST_MENU = [
  {
    id: 'b01',
    name: '招牌烤雞腿飯盒',
    category: '招牌飯盒',
    price: 150,
    desc: '去骨雞腿以特製醬汁醃製，烤至金黃酥香，外皮微脆、肉質多汁。',
    tag: '大推',
    image: '🍗',
  },
  {
    id: 'b02',
    name: '醬烤牛肉片飯盒',
    category: '招牌飯盒',
    price: 150,
    desc: '精選牛肉片搭配韓式醬汁炭火炙烤，帶有迷人烤肉風味。',
    tag: '烤肉風味',
    image: '🥩',
  },
  {
    id: 'b03',
    name: '原燒松阪豬飯盒',
    category: '招牌飯盒',
    price: 180,
    desc: '新鮮松阪豬以原味炭烤，外酥內嫩，撒上蒜香粉更添層次。',
    image: '🥓',
  },
  {
    id: 'b04',
    name: '薄鹽烤鮭魚飯盒',
    category: '招牌飯盒',
    price: 180,
    desc: '北海道風薄鹽鮭魚，油脂豐厚、鹹度適中，單純烤出鮮甜。',
    image: '🍣',
  },
  {
    id: 'b05',
    name: '頂級板腱牛排飯盒',
    category: '招牌飯盒',
    price: 250,
    desc: '油花豐富、肉質紮實，烤後多汁甘甜，適合想吃飽又吃好的人。',
    image: '🥩',
  },
  {
    id: 'b06',
    name: '私房鹹豬肉飯盒',
    category: '招牌飯盒',
    price: 150,
    desc: '獨門醬汁醃漬，烤至外皮酥香、內裡軟嫩，老饕必點。',
    tag: '老饕最愛',
    image: '🍖',
  },
  {
    id: 'b07',
    name: '挪威烤鯖魚飯盒',
    category: '招牌飯盒',
    price: 130,
    desc: '薄鹽挪威鯖魚，低熱量、簡單炭烤，鮮香不膩。',
    tag: '人氣',
    image: '🐟',
  },
  {
    id: 'b08',
    name: '醬烤梅花豬飯盒',
    category: '招牌飯盒',
    price: 120,
    desc: '梅花豬片刷上獨門烤醬炙烤，香氣十足、入口軟嫩。',
    image: '🐷',
  },
  {
    id: 'b09',
    name: '蒲燒烤鯛魚飯盒',
    category: '招牌飯盒',
    price: 120,
    desc: '去骨鯛魚腹以日式蒲燒醬炭烤，甜鹹平衡、魚肉細嫩。',
    image: '🐠',
  },
  {
    id: 'b10',
    name: '椒鹽杏鮑菇飯盒',
    category: '招牌飯盒',
    price: 120,
    desc: '杏鮑菇椒鹽炭烤，鮮嫩多汁，方便素也可安心享用。',
    tag: '方便素',
    image: '🍄',
  },
  {
    id: 'sp00',
    name: '雞油拌飯盒',
    category: '特別餐點',
    price: 80,
    desc: '雞油拌飯，簡單滿足、實惠好入口。',
    image: '🍚',
  },
  {
    id: 'sp01',
    name: '小菜飯盒',
    category: '特別餐點',
    price: 80,
    desc: '小菜飯盒，簡單滿足、實惠好入口。',
    image: '🍚',
  },
  {
    id: 'sp02',
    name: '全素飯盒',
    category: '特別餐點',
    price: null,
    priceLabel: '請詢價',
    inquire: true,
    desc: '全素配方，實際內容與價格請向店家確認。',
    image: '🥬',
  },
  {
    id: 'sp03',
    name: '每日例湯',
    category: '特別餐點',
    price: 30,
    desc: '每日更換湯品，溫熱搭配飯盒剛剛好。',
    image: '🥣',
  },
  {
    id: 'sp04',
    name: '瓶裝冷泡茶 600cc',
    category: '特別餐點',
    price: 60,
    desc: '清爽冷泡茶，解膩好搭。',
    image: '🧋',
  },
  {
    id: 'sp05',
    name: '隱藏版限量飯盒',
    category: '特別餐點',
    price: null,
    priceLabel: '$120–$390',
    inquire: true,
    needBooking: true,
    desc: '主廚季節限定，需提前預約，實際品項與價格依當日為準。',
    tag: '需預約',
    image: '✨',
  },
  {
    id: 'a01',
    name: '單點・雞腿',
    category: '人氣單點',
    price: 90,
    desc: '招牌烤雞腿單點份量。',
    image: '🍗',
  },
  {
    id: 'a02',
    name: '單點・牛片',
    category: '人氣單點',
    price: 90,
    desc: '醬烤牛肉片單點份量。',
    image: '🥩',
  },
  {
    id: 'a03',
    name: '單點・鹹豬',
    category: '人氣單點',
    price: 90,
    desc: '私房鹹豬肉單點份量。',
    image: '🍖',
  },
  {
    id: 'a04',
    name: '單點・鮭魚',
    category: '人氣單點',
    price: 100,
    desc: '薄鹽烤鮭魚單點份量。',
    image: '🍣',
  },
  {
    id: 'a05',
    name: '單點・松阪',
    category: '人氣單點',
    price: 120,
    desc: '原燒松阪豬單點份量。',
    image: '🥓',
  },
  {
    id: 'a06',
    name: '單點・板腱牛排',
    category: '人氣單點',
    price: 180,
    desc: '頂級板腱牛排單點份量。',
    image: '🥩',
  },
  {
    id: 'a07',
    name: '單點・燙青菜',
    category: '人氣單點',
    price: 50,
    desc: '燙青菜單點。',
    image: '🥦',
  },
  {
    id: 'a08',
    name: '單點・杏鮑菇',
    category: '人氣單點',
    price: 60,
    desc: '椒鹽杏鮑菇單點份量。',
    image: '🍄',
  },
  {
    id: 'a09',
    name: '單點・鯛魚',
    category: '人氣單點',
    price: 60,
    desc: '蒲燒烤鯛魚單點份量。',
    image: '🐠',
  },
  {
    id: 'a10',
    name: '單點・梅豬',
    category: '人氣單點',
    price: 60,
    desc: '醬烤梅花豬單點份量。',
    image: '🐷',
  },
  {
    id: 'a11',
    name: '單點・雙腸',
    category: '人氣單點',
    price: 70,
    desc: '雙腸單點。',
    image: '🌭',
  },
  {
    id: 'a12',
    name: '單點・鯖魚',
    category: '人氣單點',
    price: 70,
    desc: '挪威烤鯖魚單點份量。',
    image: '🐟',
  },
  {
    id: 'f01',
    name: 'Minibox 水果杯',
    category: '營養選擇',
    price: 50,
    needBooking: true,
    desc: '內含四種水果。請提前一天預約（天天五蔬果）。',
    tag: '需預約',
    image: '🍎',
  },
];
